### ISSUE TITLE
Allow action with all types.

### ISSUE THREAD

**Issue by bkhall** [tingyik90/snackprogressbar#11]
As currently implemented, one cannot set an action (that displays) when using a SnackProgressBar type other than type ACTION.

We need to be able to use DETERMINATE and INDETERMINATE types (for the progress indicators) to properly follow async background operations, and provide the user a way to cancel the operations, if necessary.

Additionally, for type INDETERMINATE, please use the same horizontal progress styling as shown in type DETERMINATE, or provide a method to allow the developer to choose which progress indicator style.

**Comment by tingyik90** [comment]
Hi, this seems to be a valid direction for this library. Give me some time and I will add it in.

**Comment by bkhall** [comment]
I've had some time to look at this more closely. While the feature would still be useful, say to retry a failed async task...using it to cancel a task that is in progress is not consistent with the Material Design Guidelines.

From the docs:
Only one snackbar may be displayed at a time. Each snackbar may contain a single action, neither of which may be “Dismiss” or “Cancel.”

**Comment by tingyik90** [comment]
This library already deviates from the Material Design Guidelines since day one, because

1. We are never supposed to prevent user input by blocking the UI. This is the reason ProgressDialog is deprecated in Android O.
2. Snackbar is not supposed to have progress bar.
3. Snackbar is not supposed to have icon.

Frankly, I think Material Design is great, but it is also a growing document that Google themselves are also making a mess sometimes. It should not be viewed as a strict set of rules. I'm doing my best to adhere to most of the guidelines e.g. grid and keylines, but also further expand on them.

In your context, having a "cancel" button is perfectly reasonable since that is how you will interact with a progress (not snackbar).

**Comment by bkhall** [comment]
Good points. In that case, press on.

We made extensive use of the progress dialog in our app(s), because while the data is loading, interaction *should* be blocked. Taking it away while not providing an alternative that complies with their other Guidelines is short sighted in my opinion. Maybe it'll come when the ProgressDialog is actually removed, instead of just deprecated.

**Comment by tingyik90** [comment]
Library updated to v4.0 to include this feature. Please give it a try.
