### ISSUE TITLE
instant dismiss is not working

### ISSUE THREAD

**Issue by ligi** [tingyik90/snackprogressbar#26]
`snackProgressBarManager.show` followed by an instant `snackProgressBarManager.dismiss()` or `snackProgressBarManager.dismissAll()` leads to dismiss not working as intended and the snack still being present.

**Comment by tingyik90** [comment]
Hi @ligi, really thank you for looking into this library. Yes, you are right, instant dismiss has been an issue since day 1 actually and I haven't a clue about why it happened, until now. Please see the latest commit https://github.com/tingyik90/snackprogressbar/commit/99edfdbe060a9ee9627de9de85187f49f98e9039. It should solve this issue now. Tested and working, but I look forward to your confirmation. Will release as 6.1.2 if working properly.

**Comment by ligi** [comment]
yes that works - please release 6.1.2 - would look nicer in my gradle files then ;-)

**Comment by tingyik90** [comment]
Thanks for the confirmation! Just to clarify #27 and I will release 6.2.0 instead, since #28 introduce some change to how the queue works.
