### ISSUE TITLE
How to move views inside ConstraintLayout?

### ISSUE THREAD

**Issue by starsep** [tingyik90/snackprogressbar#4]
In one activity where main layout is `android.support.design.widget.CoordinatorLayout` moving fab works fine. But in other activity root is `android.support.constraint.ConstraintLayout` and even though I added two buttons with `setViewsToMove` they don't seem affected in any way by showing `SnackProgressBar`.

Is it expected behavior? Maybe I'm doing sth wrong?
I can provide some minimal example if needed.

**Comment by tingyik90** [comment]
Just a quick question first. Did you have `android:animateLayoutChanges="true"` in your ConstraintLayout xml?

**Comment by starsep** [comment]
I didn't have that, but adding it doesn't seem to do a trick.

**Comment by tingyik90** [comment]
I just tried out with ConstraintLayout and have no issue with moving the buttons or even a mixture of different views. I guess this happened because you have a rather complicated layout. Are those buttons actually encapsulated by a Linear / Relative Layout that has "wrap_content"? Based on my experience, when animating a view, we are moving a view relative to a parent. So if the parent is already wrapping the view, nothing will happen. If that is the case, try moving the parent layout instead.

Post your xml here if it is still not working. I'll have a look when free.

**Comment by tingyik90** [comment]
Is your problem solved? I'm closing this soon.
